# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'counselor_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(852, 497)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_modify_account = QtWidgets.QPushButton(Dialog)
        self.pushButton_modify_account.setObjectName("pushButton_modify_account")
        self.horizontalLayout_2.addWidget(self.pushButton_modify_account)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_enable_account = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_enable_account.setObjectName("lineEdit_enable_account")
        self.horizontalLayout_3.addWidget(self.lineEdit_enable_account)
        self.pushButton_enable_account = QtWidgets.QPushButton(Dialog)
        self.pushButton_enable_account.setObjectName("pushButton_enable_account")
        self.horizontalLayout_3.addWidget(self.pushButton_enable_account)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_init_account = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_init_account.setObjectName("lineEdit_init_account")
        self.horizontalLayout_4.addWidget(self.lineEdit_init_account)
        self.pushButton_init_account = QtWidgets.QPushButton(Dialog)
        self.pushButton_init_account.setObjectName("pushButton_init_account")
        self.horizontalLayout_4.addWidget(self.pushButton_init_account)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.comboBox_request_type = QtWidgets.QComboBox(Dialog)
        self.comboBox_request_type.setObjectName("comboBox_request_type")
        self.horizontalLayout_5.addWidget(self.comboBox_request_type)
        self.lineEdit_request_id = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_request_id.setObjectName("lineEdit_request_id")
        self.horizontalLayout_5.addWidget(self.lineEdit_request_id)
        self.pushButton_examine = QtWidgets.QPushButton(Dialog)
        self.pushButton_examine.setObjectName("pushButton_examine")
        self.horizontalLayout_5.addWidget(self.pushButton_examine)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.label_state = QtWidgets.QLabel(Dialog)
        self.label_state.setText("")
        self.label_state.setObjectName("label_state")
        self.verticalLayout_2.addWidget(self.label_state)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_modify_account.setText(_translate("Dialog", "修改账号"))
        self.pushButton_enable_account.setText(_translate("Dialog", "解封学生账号"))
        self.pushButton_init_account.setText(_translate("Dialog", "初始化学生账号"))
        self.pushButton_examine.setText(_translate("Dialog", "审批"))
