# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'issue_leave_request_windowui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(245, 339)
        self.comboBox_request_type = QtWidgets.QComboBox(Dialog)
        self.comboBox_request_type.setGeometry(QtCore.QRect(70, 10, 150, 20))
        self.comboBox_request_type.setObjectName("comboBox_request_type")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 58, 20))
        self.label.setObjectName("label")
        self.dateTimeEdit_start = QtWidgets.QDateTimeEdit(Dialog)
        self.dateTimeEdit_start.setGeometry(QtCore.QRect(70, 40, 161, 31))
        self.dateTimeEdit_start.setObjectName("dateTimeEdit_start")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 45, 58, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 85, 58, 21))
        self.label_3.setObjectName("label_3")
        self.dateTimeEdit_end = QtWidgets.QDateTimeEdit(Dialog)
        self.dateTimeEdit_end.setGeometry(QtCore.QRect(70, 80, 161, 31))
        self.dateTimeEdit_end.setObjectName("dateTimeEdit_end")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(80, 120, 91, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit_leave_reason = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_leave_reason.setGeometry(QtCore.QRect(10, 150, 221, 141))
        self.lineEdit_leave_reason.setObjectName("lineEdit_leave_reason")
        self.pushButton_submit = QtWidgets.QPushButton(Dialog)
        self.pushButton_submit.setGeometry(QtCore.QRect(60, 300, 112, 32))
        self.pushButton_submit.setObjectName("pushButton_submit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "请假类型"))
        self.label_2.setText(_translate("Dialog", "开始时间"))
        self.label_3.setText(_translate("Dialog", "结束时间"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt;\">请假理由</span></p></body></html>"))
        self.pushButton_submit.setText(_translate("Dialog", "提交"))
