# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modify_account_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(459, 284)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 421, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_new_token = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_new_token.setObjectName("lineEdit_new_token")
        self.horizontalLayout.addWidget(self.lineEdit_new_token)
        self.pushButton_modify_token = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_modify_token.setObjectName("pushButton_modify_token")
        self.horizontalLayout.addWidget(self.pushButton_modify_token)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 60, 421, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_close_dual_auth = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_close_dual_auth.setObjectName("pushButton_close_dual_auth")
        self.horizontalLayout_2.addWidget(self.pushButton_close_dual_auth)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 110, 421, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_new_account = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_new_account.setObjectName("lineEdit_new_account")
        self.horizontalLayout_3.addWidget(self.lineEdit_new_account)
        self.pushButton_modify_account = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_modify_account.setObjectName("pushButton_modify_account")
        self.horizontalLayout_3.addWidget(self.pushButton_modify_account)
        self.pushButton_confirm = QtWidgets.QPushButton(Dialog)
        self.pushButton_confirm.setGeometry(QtCore.QRect(170, 240, 112, 32))
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 160, 421, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_new_password = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_new_password.setObjectName("lineEdit_new_password")
        self.horizontalLayout_4.addWidget(self.lineEdit_new_password)
        self.pushButton_modify_password = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_modify_password.setObjectName("pushButton_modify_password")
        self.horizontalLayout_4.addWidget(self.pushButton_modify_password)
        self.label_state = QtWidgets.QLabel(Dialog)
        self.label_state.setGeometry(QtCore.QRect(50, 210, 361, 16))
        self.label_state.setText("")
        self.label_state.setObjectName("label_state")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "新口令："))
        self.pushButton_modify_token.setText(_translate("Dialog", "打开双重认证/修改口令"))
        self.pushButton_close_dual_auth.setText(_translate("Dialog", "关闭双重认证"))
        self.label_3.setText(_translate("Dialog", "新账号："))
        self.pushButton_modify_account.setText(_translate("Dialog", "修改账号"))
        self.pushButton_confirm.setText(_translate("Dialog", "确定"))
        self.label_4.setText(_translate("Dialog", "新密码："))
        self.pushButton_modify_password.setText(_translate("Dialog", "修改密码"))
