# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(739, 477)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_modify_account = QtWidgets.QPushButton(Dialog)
        self.pushButton_modify_account.setObjectName("pushButton_modify_account")
        self.horizontalLayout_3.addWidget(self.pushButton_modify_account)
        self.pushButton_issue_request = QtWidgets.QPushButton(Dialog)
        self.pushButton_issue_request.setObjectName("pushButton_issue_request")
        self.horizontalLayout_3.addWidget(self.pushButton_issue_request)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_withdraw_request = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_withdraw_request.setObjectName("lineEdit_withdraw_request")
        self.horizontalLayout.addWidget(self.lineEdit_withdraw_request)
        self.pushButton_withdraw = QtWidgets.QPushButton(Dialog)
        self.pushButton_withdraw.setObjectName("pushButton_withdraw")
        self.horizontalLayout.addWidget(self.pushButton_withdraw)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget_request = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_request.setObjectName("tableWidget_request")
        self.tableWidget_request.setColumnCount(0)
        self.tableWidget_request.setRowCount(0)
        self.tableWidget_request.horizontalHeader().setVisible(True)
        self.verticalLayout.addWidget(self.tableWidget_request)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_modify_account.setText(_translate("Dialog", "账号修改"))
        self.pushButton_issue_request.setText(_translate("Dialog", "请假"))
        self.pushButton_withdraw.setText(_translate("Dialog", "撤回"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">我的请假请求</span></p></body></html>"))
