# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teacher_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(523, 376)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_modify_account = QtWidgets.QPushButton(Dialog)
        self.pushButton_modify_account.setObjectName("pushButton_modify_account")
        self.verticalLayout.addWidget(self.pushButton_modify_account)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_confirm_read_request_id = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_confirm_read_request_id.setObjectName("lineEdit_confirm_read_request_id")
        self.verticalLayout.addWidget(self.lineEdit_confirm_read_request_id)
        self.pushButton_confirm_read = QtWidgets.QPushButton(Dialog)
        self.pushButton_confirm_read.setObjectName("pushButton_confirm_read")
        self.verticalLayout.addWidget(self.pushButton_confirm_read)
        self.tableWidget_list = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_list.setObjectName("tableWidget_list")
        self.tableWidget_list.setColumnCount(0)
        self.tableWidget_list.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_list)
        self.label_state = QtWidgets.QLabel(Dialog)
        self.label_state.setText("")
        self.label_state.setObjectName("label_state")
        self.verticalLayout.addWidget(self.label_state)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_modify_account.setText(_translate("Dialog", "修改账号"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">已读确认请假编号</p></body></html>"))
        self.pushButton_confirm_read.setText(_translate("Dialog", "已读确认"))
